openapi: 3.0.0
info:
  title: API de Gestión de Pacientes
  version: 1.0.0
  description: API para el CRUD (Crear, Consultar, Actualizar, Desactivar) de pacientes.

servers:
  - url: http://localhost:3000/api/v1/clinical/manage-clinical-records
    description: Entorno de desarrollo local (API Gateway).

paths:
  /registerClinicalRecord:
    post:
      summary: Registrar nueva historia clínica
      tags:
        - Historias Clínicas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClinicalRecordSchema'
      responses:
        '201':
          description: Historia Clínica registrada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClinicalRecordSchema'

        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerInternalError'
          
  
  /updateClinicalRecord:
    patch:
      summary: Actualizar Historia Clínica
      tags:
        - Historias Clínicas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdRequiredSchema'
      responses:
        '200':
          description: Datos de la historia clínica actualizados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClinicalRecordSchema'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerInternalError'
        '404':
          $ref: '#/components/responses/NotFound'
          
  /searchClinicalRecord:
    get:
      summary: Consultar historia clínica por Identificador Único
      tags:
        - Historias Clínicas
      parameters:
        - in: query
          name: identifier
          schema:
            type: string
            format: ObjectId
          required: true
          description: Identificador único de la Historia Clínica .
      responses:
        '200':
          description: Historia Clínica Consultado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClinicalRecordSchema'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerInternalError'
        '404':
          $ref: '#/components/responses/NotFound'

  /deleteClinicalRecord:
    post:
      summary: Eliminar Historia Clínica
      tags:
        - Historias Clínicas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Datos requeridos para eliminar la Historia Clínica.
              required:
                - identifier
              properties:
                identifier:
                  type: string
                  nullable: false
                  description: Identificador único de la Historia Clínica.
                  example: "123456"
      responses:
        '200':
          description: Historia Clínica eliminada.
          content:
            application/json:
              schema:
                type: object
                description: Historia Clínica eliminada
                properties:
                  identifier:
                    type: string
                    nullable: false
                    description: Identificador único de la historia clínica.
                    example: "123456"
                  message:
                    type: string
                    nullable: false
                    description: Mensaje de eliminación.
                    example: Historia Clínica eliminada correctamente.
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerInternalError'
        '404':
          $ref: '#/components/responses/NotFound'

components:

  schemas:
    ClinicalRecordSchema:
      type: object
      description: Datos Historia Clínica.
      properties:
        identifier:
          type: string
          nullable: false
          description: Identificador único de la historia clínica.
          example: "123456"
        patientId:
          type: string
          nullable: false
          description: Documento único del paciente.
          example: "45678"
        tumorTypedId:
          type: string
          nullable: false
          description: Identificador único del tipo de tumor.
          example: 2000-10-25.
        diagnosisDate:
          type: string
          nullable: false
          description: Fecha del diagnóstico.
          example: 2000-10-25.
        stage:
          type: string
          nullable: false
          description: Etapa del Tumor.
          example: IIV
        treatmentProtocol:
          type: string
          nullable: false
          description: Protocolo Tratamiento.
          example: Quimioterapia
    IdRequiredSchema:
      type: object
      description: Datos requeridos para actualizar una Historia Clínica.
      required:
        - identifier
      properties:
        identifier:
          type: string
          nullable: false
          description: Identificador único de la historia clínica.
          example: "123456"
        patientId:
          type: string
          nullable: false
          description: Documento único del paciente.
          example: "45678"
        tumorTypedId:
          type: string
          nullable: false
          description: Identificador único del tipo de tumor.
          example: 2000-10-25.
        diagnosisDate:
          type: string
          nullable: false
          description: Fecha del diagnóstico.
          example: 2000-10-25.
        stage:
          type: string
          nullable: false
          description: Etapa del Tumor.
          example: IIV
        treatmentProtocol:
          type: string
          nullable: false
          description: Protocolo Tratamiento.
          example: Quimioterapia
    CreateClinicalRecordSchema:
      type: object
      description: Datos requeridos para registrar una historia clínica
      required:
        - identifier
        - patientId
        - tumorTypedId
        - diagnosisDate
        - stage
        - treatmentProtocol
      properties:
        identifier:
          type: string
          nullable: false
          description: Identificador único de la historia clínica.
          example: "123456"
        patientId:
          type: string
          nullable: false
          description: Documento único del paciente.
          example: "45678"
        tumorTypedId:
          type: string
          nullable: false
          description: Identificador único del tipo de tumor.
          example: 2000-10-25.
        diagnosisDate:
          type: string
          nullable: false
          description: Fecha del diagnóstico.
          example: 2000-10-25.
        stage:
          type: string
          nullable: false
          description: Etapa del Tumor.
          example: IIV
        treatmentProtocol:
          type: string
          nullable: false
          description: Protocolo Tratamiento.
          example: Quimioterapia
          
  responses:
    BadRequest:
          description: Bad Request - Error en la petición del cliente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: Por favor revise los campos.
    ServerInternalError:
      description: Internal Server Error - Error del servidor.
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 500
              message:
                type: string
                example: Error interno generado.
    NotFound:
      description: Historia Clínica no encontrada